apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-models
  namespace: llamastack
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
