apiVersion: v1
kind: Service
metadata:
  name: vllm-server
  namespace: llamastack
spec:
  selector:
    app.kubernetes.io/name: vllm
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP