apiVersion: v1
kind: Service
metadata:
  name: llama-stack-service
  namespace: llamastack
spec:
  selector:
    app.kubernetes.io/name: llama-stack
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
