apiVersion: v1
kind: Service
metadata:
  name: llamastack-service
  namespace: llamastack
spec:
  selector:
    app: llamastack
  ports:
    - protocol: TCP
      port: 8321
      targetPort: 8321
  type: ClusterIP