apiVersion: v1
kind: Service
metadata:
  name: llamastack
  namespace: llamastack
spec:
  selector:
    app: llamastack
  ports:
    - name: api
      port: 5001
      targetPort: 5001
    - name: ollama
      port: 11434
      targetPort: 11434